apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web
spec:
  selector:
    matchLabels:
      app: example-web
  replicas: 1
  template:
    metadata:
      labels:
        app: example-web
    spec:
      containers:
      - name: example-web
        image: example-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: k8s_namespace
            valueFrom:
              configMapKeyRef:
                name: nginx-temp-var
                key: k8s_namespace
      volumes:
        - name: nginx-temp-var
          configMap:
            name: nginx-temp-var