apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web
spec:
  selector:
    matchLabels:
      app: example-web
  replicas: 1
  template:
    metadata:
      labels:
        app: example-web
    spec:
      containers:
      - name: example-web
        image: example-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
